# Generated by Django 3.1.2 on 2020-10-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0002_auto_20201024_0618'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleModele',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
            ],
        ),
    ]
