# Generated by Django 3.1.2 on 2020-10-24 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0003_samplemodele'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='titile',
            new_name='title',
        ),
    ]
